export const ALL_FORMS_SUCCESS = 'ALL_FORMS_SUCCESS'
export const ALL_FORMS_FAIL = 'ALL_FORMS_FAIL'
export const ALL_FORMS_REQUEST = 'ALL_FORMS_REQUEST'


export const PAGINATION = 'PAGINATION'
export const FILTER_VIDEO = 'FILTER_VIDEO'
export const SEARCH = 'SEARCH'